/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/_menu'
import { Route as PlayRouteImport } from './routes/play'
import { Route as MenuIndexRouteImport } from './routes/_menu.index'
import { Route as MenuOptionsRouteImport } from './routes/_menu.options'

const MenuRoute = MenuRouteImport.update({
  id: '/_menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuOptionsRoute = MenuOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => MenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MenuIndexRoute
  '/play': typeof PlayRoute
  '/options': typeof MenuOptionsRoute
}
export interface FileRoutesByTo {
  '/play': typeof PlayRoute
  '/options': typeof MenuOptionsRoute
  '/': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_menu': typeof MenuRouteWithChildren
  '/play': typeof PlayRoute
  '/_menu/options': typeof MenuOptionsRoute
  '/_menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play' | '/options'
  fileRoutesByTo: FileRoutesByTo
  to: '/play' | '/options' | '/'
  id: '__root__' | '/_menu' | '/play' | '/_menu/options' | '/_menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MenuRoute: typeof MenuRouteWithChildren
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_menu': {
      id: '/_menu'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu/': {
      id: '/_menu/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/options': {
      id: '/_menu/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof MenuOptionsRouteImport
      parentRoute: typeof MenuRoute
    }
  }
}

interface MenuRouteChildren {
  MenuOptionsRoute: typeof MenuOptionsRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuOptionsRoute: MenuOptionsRoute,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MenuRoute: MenuRouteWithChildren,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
